### ISSUE TITLE
Issue with dialyzer attributes in copied modules.

### ISSUE THREAD

**Issue by jimsynz** [edgurgel/mimic#25]
Hey my dude.

When attempting to copy a module which contains `@dialyzer {:nowarn_function, [&Cachex.get/2, &Cachex.put/4]}` I get the following compilation error:

```
** (CaseClauseError) no case clause matching: {:error, [{'lib/core_gateway/session/cache.ex', [{1, :erl_lint, {:bad_dialyzer_attribute, {:nowarn_function, &Cachex.get/2}}}, {1, :erl_lint, {:bad_dialyzer_attribute, {:nowarn_function, &Cachex.put/4}}}]}], []}
    (mimic 1.5.0) lib/mimic/module.ex:43: Mimic.Module.rename_module/2
    (mimic 1.5.0) lib/mimic/module.ex:27: Mimic.Module.replace!/1
    (mimic 1.5.0) lib/mimic.ex:344: Mimic.copy/1
    test/test_helper.exs:4: (file)
```

Which is super weird because the attribute is valid and works when compiling normally.  Whether or not I should be opening a PR to fix Cachex's typespecs is beyond the scope of this issue 😝 

Hope you're well.
James.

**Comment by edgurgel** [comment]
Hey! 🤔 Interesting! That's definitely a first! Will check it out soon!

Hope you are well, too! 👋

**Comment by dylan-chong** [comment]
```
# elixir/lib/module.ex:2268
defp valid_dialyzer_attribute?({key, fun_arities}) when is_atom(key) do
    (key == :nowarn_function or valid_dialyzer_attribute?(key)) and
      :lists.all(
        fn
          {fun, arity} when is_atom(fun) and is_integer(arity) -> true
          _ -> false
        end,
        List.wrap(fun_arities)
      )
  end
```

Looks like your syntax is incorrect @jimsynz. The Elixir Module only accepts a kw fun:arity list.

```
  @dialyzer {:nowarn_function, fun: 0, fun2: 3}
```
