### ISSUE TITLE
Not properly resetting cover modules between app test runs in umbrella apps

### ISSUE THREAD

**Issue by jared-mackey** [edgurgel/mimic#40]
Hi, I'm having an issue running my test suite from the root of my umbrella app. Here's the error:

```
11:25:03.762 [error] Task #PID<0.1852.0> started from Mimic.Server terminating
** (MatchError) no match of right hand side value: {:error, {:cant_open_file, '/apps/app_1/Elixir.App1-566835.coverdata', :enoent}}
    (mimic 1.7.1) lib/mimic/cover.ex:32: Mimic.Cover.replace_coverdata!/3
    (elixir 1.13.3) lib/task/supervised.ex:89: Task.Supervised.invoke_mfa/2
    (elixir 1.13.3) lib/task/supervised.ex:34: Task.Supervised.reply/4
    (stdlib 3.17.1) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
Function: #Function<9.80215867/0 in Mimic.Server.handle_call/3>
    Args: []
11:25:03.769 [error] Task #PID<0.1667.0> started from #PID<0.94.0> terminating
** (stop) exited in: GenServer.call(Mimic.Server, {:reset, App1}, 60000)
    ** (EXIT) an exception was raised:
        ** (MatchError) no match of right hand side value: {:error, {:cant_open_file, '/apps/app_1/Elixir.App1-566835.coverdata', :enoent}}
            (mimic 1.7.1) lib/mimic/cover.ex:32: Mimic.Cover.replace_coverdata!/3
            (elixir 1.13.3) lib/task/supervised.ex:89: Task.Supervised.invoke_mfa/2
            (elixir 1.13.3) lib/task/supervised.ex:34: Task.Supervised.reply/4
            (stdlib 3.17.1) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
    (elixir 1.13.3) lib/gen_server.ex:1030: GenServer.call/3
    (elixir 1.13.3) lib/enum.ex:937: Enum."-each/2-lists^foreach/1-0-"/2
    (ex_unit 1.13.3) lib/ex_unit/runner.ex:64: ExUnit.Runner.run_with_trap/2
    (ex_unit 1.13.3) lib/ex_unit/runner.ex:31: ExUnit.Runner.run/2
    (elixir 1.13.3) lib/task/supervised.ex:89: Task.Supervised.invoke_mfa/2
    (elixir 1.13.3) lib/task/supervised.ex:34: Task.Supervised.reply/4
    (stdlib 3.17.1) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
Function: #Function<0.129552615/0 in ExUnit.async_run/0>
    Args: []
** (EXIT from #PID<0.94.0>) exited in: GenServer.call(Mimic.Server, {:reset, App1}, 60000)
    ** (EXIT) an exception was raised:
        ** (MatchError) no match of right hand side value: {:error, {:cant_open_file, '/apps/app_1/Elixir.App1-566835.coverdata', :enoent}}
            (mimic 1.7.1) lib/mimic/cover.ex:32: Mimic.Cover.replace_coverdata!/3
            (elixir 1.13.3) lib/task/supervised.ex:89: Task.Supervised.invoke_mfa/2
            (elixir 1.13.3) lib/task/supervised.ex:34: Task.Supervised.reply/4
            (stdlib 3.17.1) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
```

I went and added some `IO.puts` into the mimic lib to see if I can hunt it down a bit.

1. Added the `COPIED:` text to `ensure_module_copied` where it gets the coverdata_path from `Module.replace!`
2. Added `Replacing cover data for` in `replace_coverdata!` and am printing out the `original_coverdata_path` and `path`
3. Added `Deleting` in `replace_coverdata!` and am printing out both paths right before it delets.

Here's the results (trimmed up a bit wit some renaming)

```
==> app_1
Cover compiling modules ...
COPIED: /apps/app_1/Elixir.App1-566835.coverdata
COPIED: /apps/app_1/Elixir.App1.Thing-566835.coverdata

...mix test output...

Randomized with seed 421312
Replacing cover data for original: /apps/app_1/Elixir.App1.Thing-566835.coverdata
Replacing cover data for original: /apps/app_1/Elixir.App1-566835.coverdata
Replacing cover data for path: /apps/app_1/Elixir.App1.Thing.Mimic.Original.Module-566835.coverdata
Replacing cover data for path: /apps/app_1/Elixir.App1.Mimic.Original.Module-566835.coverdata
Deleting /apps/app_1/Elixir.App1.Thing.Mimic.Original.Module-566835.coverdata
Deleting /apps/app_1/Elixir.App1.Thing-566835.coverdata
Deleting /apps/app_1/Elixir.App1.Mimic.Original.Module-566835.coverdata
Deleting /apps/app_1/Elixir.App1-566835.coverdata

Generating cover results ...

...coverage results output...

Analysis includes data from imported files
["/apps/app_1/Elixir.App1.Thing-566835.coverdata",
 "/apps/app_1/Elixir.App1.Thing.Mimic.Original.Module-566835.coverdata"]
Analysis includes data from imported files
["/apps/app_1/Elixir.App1-566835.coverdata",
 "/apps/app_1/Elixir.App1.Mimic.Original.Module-566835.coverdata"]
Generated HTML coverage results in "cover" directory

==> app_2
Cover compiling modules ...

...mix test output...

Randomized with seed 421312
Replacing cover data for original: /apps/app_1/Elixir.App1-566835.coverdata
Replacing cover data for path: /apps/app_2/Elixir.App1.Mimic.Original.Module-566835.coverdata

11:25:03.762 [error] Task #PID<0.1852.0> started from Mimic.Server terminating
...rest of the same error...
```

The problem seems to exist in the second app. It appears to be using the wrong path for the original coverdata path. The file is actually located at `/apps/app_2/Elixir.App1-566835.coverdata`. It stills has the old path from when `app_1` test had ran and did not properly clear out between apps test runs. It also doesn't seem to copy the module (`COPIED`) and so it's path stored in the state is still the same from the original copy from it running in the first app.

**Comment by jared-mackey** [comment]
Could this be a regression of #12 introduced in #37? Rolling back to 1.6.0 seems to resolve the issue.

**Comment by edgurgel** [comment]
Hi @jared-mackey , thanks for the very detailed bug report. This is excellent. 

This could also be related to the considerable changes I made to the way cover is handled :thinking: https://github.com/edgurgel/mimic/pull/37

I think we need to have a proper umbrella test app for the tests as it's the second time this has been broken. Will check this out this weekend and hopefully it's an easy fix :crossed_fingers:
