### ISSUE TITLE
Latest version of mimic breaks test coverage generation

### ISSUE THREAD

**Issue by nulian** [edgurgel/mimic#53]
When I update mimic to the latest version in a project I work on it breaks test coverage.

```
12:43:43.169 [error] Task #PID<0.13868.0> started from Mimic.Server terminating
** (MatchError) no match of right hand side value: {:error, {:not_cover_compiled, Synapse.AppRequest.Application.Mimic.Original.Module}}
    (mimic 1.7.4) lib/mimic/cover.ex:52: Mimic.Cover.export_coverdata!/1
    (mimic 1.7.4) lib/mimic/cover.ex:32: Mimic.Cover.clear_module_and_import_coverdata!/3
    (elixir 1.14.2) lib/task/supervised.ex:89: Task.Supervised.invoke_mfa/2
    (elixir 1.14.2) lib/task/supervised.ex:34: Task.Supervised.reply/4
    (stdlib 4.2) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
Function: #Function<9.132716098/0 in Mimic.Server.handle_call/3>
```

**Comment by dylan-chong** [comment]
Yikes this would  have been me. Can you provide some replication steps?

**Comment by nulian** [comment]
It's in a pretty big project so don't have a good simple example case not sure how it get's triggered.
Think it might be because the project still uses for some older mocks the old elixir mock library and maybe that conflicts.

**Comment by edgurgel** [comment]
> Think it might be because the project still uses for some older mocks from the old elixir mock library and maybe that conflicts.

That's very much possible! We didn't architect Mimic to work with other libraries that also touch on the cover data :thinking:

**Comment by ricksonoliveira** [comment]
Any updates on this? getting this same on a project

**Comment by ricksonoliveira** [comment]
@edgurgel  @dylan-chong

**Comment by edgurgel** [comment]
Hi team if we have a simple way to replicate the issue we can investigate

**Comment by ricksonoliveira** [comment]
To replicate this you just need to have another mock lib along with Mimic, in my case I have the [mock](https://github.com/jjh42/mock) lib and the coveralls lib, and have at least one test using the Mock and other using Mimic, then try to run `mix coveralls`
