### ISSUE TITLE
GenServer Mimic.Server terminating with elixir 1.18.0-rc.0

### ISSUE THREAD

**Issue by MrYawe** [edgurgel/mimic#87]
With:
* elixir 1.18.0-rc.0
* erlang 27.1.3
* mimic 1.10.2

```elixir
10:34:36.510 [error] GenServer Mimic.Server terminating
     ** (KeyError) key :required not found in: %{default: nil, field: :name}
         (mimic 1.10.2) lib/mimic/module.ex:128: anonymous fn/1 in Mimic.Module.generate_mimic_struct/1
         (elixir 1.18.0-rc.0) lib/enum.ex:2354: anonymous fn/3 in Enum.split_with/2
         (elixir 1.18.0-rc.0) lib/enum.ex:2546: Enum."-split_with/2-lists^foldl/2-1-"/3
         (elixir 1.18.0-rc.0) lib/enum.ex:2546: Enum.split_with/2
         (mimic 1.10.2) lib/mimic/module.ex:128: Mimic.Module.generate_mimic_struct/1
         (mimic 1.10.2) lib/mimic/module.ex:118: Mimic.Module.create_mock/2
         (mimic 1.10.2) lib/mimic/module.ex:37: Mimic.Module.replace!/2
         (mimic 1.10.2) lib/mimic/server.ex:525: Mimic.Server.ensure_module_copied/2
         (mimic 1.10.2) lib/mimic/server.ex:284: Mimic.Server.handle_call/3
         (stdlib 6.1.2) gen_server.erl:2381: :gen_server.try_handle_call/4
         (stdlib 6.1.2) gen_server.erl:2410: :gen_server.handle_msg/6
         (stdlib 6.1.2) proc_lib.erl:329: :proc_lib.init_p_do_apply/3
```

**Comment by edgurgel** [comment]
1.10 is out!
